### ISSUE TITLE
1.77 available

### ISSUE THREAD

**Issue by elect86** [kotlin-graphics/imgui#155]
I just completed and merged 1.77 back into master (`-jdk8` variant as well)

Feel free to try out and leave some feedbacks in case of bug or features

**Comment by Dj-jom2x** [comment]
will u update the kotlin to 1.4.10  ... after this intellij update 1.4.0 to 1.4.10 im having this error

```
java.lang.LinkageError: loader constraint violation: when resolving method "imgui.ImGui.begin(Ljava/lang/String;Lkotlin/reflect/KMutableProperty0;I)Z" the class loader (instance of net/fabricmc/loader/launch/knot/KnotClassLoader) of the current class, net/aaa/bbbb/gui/screen/ModScreen, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, imgui/ImGui, have different Class objects for the type kotlin/reflect/KMutableProperty0 used in the signature
```

error occur when i use this 

```
MutableProperty0<Boolean> show_console = new MutableProperty0<Boolean>(false);
```
it works before tho I dint even touch anything. ngl I don't understand what is that error above xD 
```
 imgui/ImGui, have different Class objects for the type kotlin/reflect/KMutableProperty0 used in the signature
```

**Comment by Dj-jom2x** [comment]
after updating to 1.77 btw just now I receive this

```
java.lang.NoSuchMethodError: uno.glfw.GlfwWindow.getHandle()J
	at imgui.impl.glfw.ImplGlfw.<init>(ImplGlfw.kt:79)
```
hmmmmm xD wait i see you update again in 15mins ago.. leme try to redownload..

**Comment by elect86** [comment]
There seems to be some issues with kotlin reflect, I directly updated to 1.4.10, the example runs fine

Give it a try.

Also, `NoSuchMethodError` suggests your project is using an old uno, pull explicitely against 2599943c

**Comment by Dj-jom2x** [comment]
> There seems to be some issues with kotlin reflect, I directly updated to 1.4.10, the example runs fine (branch `jdk8-1.4.10`)
> 
> Give it a try.
> 
> Also, `NoSuchMethodError` suggests your project is using an old uno, pull explicitely against 2599943c

I invalidate the cache and restart. also tried to delete those jars so Gradle will forcely download the jar again.. how do i fix not using old uno?

```graddle

    ["gl", "glfw", "core"].each {
        implementation("com.github.kotlin-graphics.imgui:imgui-$it:jdk8-SNAPSHOT") {
            exclude group: "org.lwjgl"
        }
    }

    implementation "com.github.kotlin-graphics:uno-sdk:jdk8-SNAPSHOT"
    implementation "com.github.kotlin-graphics:glm:jdk8-SNAPSHOT"
    implementation group: 'org.jetbrains.kotlin', name: 'kotlin-reflect', version: '1.4.10'
```

so its a jdk8_1.4.10-SNAPSHOT now? wait im going to try that... 

update: it doesnt work xD wait do I remove the snapshot. what changes?

**Comment by Dj-jom2x** [comment]
I can't download it.. hmm what did I miss xD 

![image](https://user-images.githubusercontent.com/12135498/93594338-3e3aef00-f9e8-11ea-9b6d-439d92fc0f4c.png)

**Comment by elect86** [comment]
```
["gl", "glfw", "core"].each {
        implementation("com.github.kotlin-graphics.imgui:$it:4603278f") { // let be explicit here, also now it's just "imgui:$it" instead "imgui:imgui-$it", I'm gonna update the wiki
            exclude group: "org.lwjgl"
        }
}
```

`implementation "com.github.kotlin-graphics:uno-sdk:2599943c"` let's be explicit here as well

Please note that the autobuild features on push on Jitpack is not reliable, so when you are the very first to pull a commit and this isn't available (ie: build yet), that attempt will probably fail because of timeout, so you have to pull it once again (because in the meanwhile Jitpack has completed). You can follow the status directly on https://jitpack.io/#kotlin-graphics/imgui

**Comment by Dj-jom2x** [comment]
oooo thats new btw I think it failed to build "https://jitpack.io/com/github/kotlin-graphics/imgui/jdk8_1.4.10-1e22d55958-1/build.log" 
 
but I will try that 4603278f

**Comment by Dj-jom2x** [comment]
hmm last error? glm? i put 2599943c xD 

![image](https://user-images.githubusercontent.com/12135498/93600118-bc4fc380-f9f1-11ea-8829-eb31e0c00252.png)

**Comment by elect86** [comment]
use `557908c3` for glm

**Comment by Dj-jom2x** [comment]
> use `557908c3` for glm

i did that now i have this 
![image](https://user-images.githubusercontent.com/12135498/93603885-359de500-f9f7-11ea-9ac6-e1307d09e8ef.png)

is it because I exclude this?

```
 ["gl", "glfw", "core"].each {
        implementation("com.github.kotlin-graphics.imgui:$it:4603278f") {
            exclude group: "org.lwjgl"
        }
    }
```

but I can't un exclude it because I use it in Minecraft. Minecraft has its own lwjgl. and i really dint change anything on my graddle this all works before even i exclude it

**Comment by elect86** [comment]
Well, actually (I suppose) you don't need opengles, jawt or vulkan

We may try with a custom branch only for Minecraft, if you want

**Comment by Dj-jom2x** [comment]
The last resort I can do is to go back with 
```
public boolean begin(@NotNull String name,
                     @NotNull boolean[] pOpen,
                     int flags)
```
the boolean[] and not KMutableProperty0 one.. the KMutableProperty0 one looks neat but I guess i have to use the array again xD .. also I will keep my eye peeled on your updates :)

**Comment by elect86** [comment]
Anyway, is your project public?

**Comment by Dj-jom2x** [comment]
> Anyway, is your project public?

nope, it's private I can give u access or I guess i can make a repo. that we can play around. after I eat.. that's easy to reproduce. :)

**Comment by Dj-jom2x** [comment]
I think its fixed.. but.. no combo filter

Fresh setup .. fresh everything.. u still cant run MutableProperty0 .. but  it works now if you copy and paste it on your source code .. and name it somethign else like KotlinMutation.. 

so whats in my C:\,........................gradle\caches\modules-2\files-2.1\com.github.kotlin-graphics.imgui\core\4603278f\b5497481b532f7da4fd3308203013589cb1a27d7

the "4603278f" exist so it means im using it

when i try to trace the declaration of combo.. just to see if the combofilter is there nope


```kotlin
 
/** Widgets: Combo Box
 *  - The BeginCombo()/EndCombo() api allows you to manage your contents and selection state however you want it, by creating e.g. Selectable() items.
 *  - The old Combo() api are helpers over BeginCombo()/EndCombo() which are kept available for convenience purpose.    */
interface widgetsComboBox {

    fun beginCombo(label: String, previewValue: String?, flags_: ComboFlags = 0): Boolean {
		.............
    }

    /** Only call EndCombo() if BeginCombo() returns true! */
    fun endCombo() = endPopup()

    /** Combo box helper allowing to pass an array of strings.  */
    fun combo(label: String, currentItem: KMutableProperty0<Int>, items: Array<String>, heightInItems: Int = -1): Boolean =
            combo(label, currentItem, items.toList(), heightInItems)

    /** Combo box helper allowing to pass all items in a single string literal holding multiple zero-terminated items "item1\0item2\0" */
    fun combo(label: String, currentItem: IntArray, itemsSeparatedByZeros: String, heightInItems: Int = -1): Boolean {
      .............
    }

    fun combo(label: String, currentItem: KMutableProperty0<Int>, itemsSeparatedByZeros: String, heightInItems: Int = -1): Boolean {
       .............
    }

    /** Combo box function. */
    fun combo(label: String, currentItem: IntArray, items: List<String>, popupMaxHeightInItem: Int = -1): Boolean {
       .............
    }

    fun combo(label: String, currentItemPtr: KMutableProperty0<Int>, items: List<String>, popupMaxHeightInItem: Int = -1): Boolean {

       ............
    }

    /** Old API, prefer using BeginCombo() nowadays if you can. */
    fun combo(label: String, pCurrentItem: KMutableProperty0<Int>, itemsGetter: (Array<String>, Int, KMutableProperty0<String>) -> Boolean,
              items: Array<String>, popupMaxHeightInItems: Int = -1): Boolean {
			.............
    }

    ..............
}
```

its not exist... 

![image](https://user-images.githubusercontent.com/12135498/93629990-cab2d500-fa1b-11ea-80d1-f3fc00be6bed.png)

btw here's the repo that we can play https://github.com/Dj-jom2x/fabric-kotlin-graphics

**Comment by elect86** [comment]
Sorry, my bad, I messed up and left it in master only, it should be there with 43281293

**Comment by Dj-jom2x** [comment]
> 4328129

kewl I will wait for it on 'https://jitpack.io/#kotlin-graphics/imgui', right?  aight I'm going to wait.

**Comment by elect86** [comment]
You need to pull once to trigger the build though

**Comment by Dj-jom2x** [comment]
4328129 commit fixes the MutableProperty0 usage in java 8 ... thanks.. about combo filter...

Am I doing it right in java?

```java
    byte[] lol = new byte[256];

    String[] hint = new String[]{"hello", "hi", "what"};

    ComboFilterState state = new ComboFilterState();


......... render function
 if (comboFilter("yeah", lol, hint, state, 0)) {

 }

```

it looks like this 

![image](https://user-images.githubusercontent.com/12135498/93685940-90ae0580-fae5-11ea-81e9-5f13109df417.png)


 

overall it looks lit.. <3 the last thing we need to work is filtering. 

* It should only filter that matches with the start of the string...
* Don't force it open if the user dints select anything just keep the previous selection and close it.
* At the first run, it should be close as default.


I think i will move at https://github.com/kotlin-graphics/imgui/issues/145 now since 1.77 is lit already,.

**Comment by elect86** [comment]
ah, you want it to filter and cut out what it doesnt match..

the way it is implemented now is jumping directly to the match 

Also, it's closed by default.. do you see it open?

**Comment by Dj-jom2x** [comment]
sorry late reply
> ah, you want it to filter and cut out what it doesnt match..

~ yeah and gather all stuff that slight match on that search.. maybe optional.

> Also, it's closed by default.. do you see it open?

~ yes on java that code above posted makes it automatically open at first and u are forced to select something else it stays open. but in kotlin it works perfectly great

**Comment by elect86** [comment]
weird.. is your playground project updated?

**Comment by elect86** [comment]
I'm closing this since 1.77 has been just released

@Dj-jom2x if you want we cant continue nonetheless..
